version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: python ../main.py
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: free -g
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
