version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip3 install awscli --upgrade --user
      - run: aws s3 sync --no-sign-request s3://openneuro.org/ds001506 ds001506-download/
      - run: cd ds001506-download/ && ls -sh
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: cd ds001506-download/ && ls -sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
