name: Redis Service Example

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image:  node:10.16-jessie

    services:
    steps:
    - run: npm ci

